apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlight
  labels:
    css: ze
spec:
  selector:
    matchLabels:
      css: ze
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        css: ze
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: gitlab
      containers:
        - name: torchlight
          image: 'supremeelite/torchlight3:latest'
          imagePullPolicy: Always
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 2
            timeoutSeconds: 10
            tcpSocket:
              host: ''
              port: 27025
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
            tcpSocket:
              host: ''
              port: 27025